apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mini-node-exporter
  name: mini-node-exporter
spec:
  containers:
    - image: yuhuashi1117/mini-node-exporter
      name: mini-node-exporter
      command: ["yarn"]
      args: ["start"]
      resources:
        limits:
          memory: "128Mi"
          cpu: "50m"
  restartPolicy: OnFailure
