apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  default: |
    global:
      scrape_interval:     5s 
      evaluation_interval: 10s
    scrape_configs:
        - job_name: mini-node-exporter
          static_configs:
            - targets: ['mini-node-exporter-svc.default.svc.cluster.local:23333']
